name: CI/CD for BAW Project 

on:
  workflow_dispatch:

jobs:
  install_package:
    runs-on: ubuntu-latest
    env:
      ZEN_API_KEY: ${{ secrets.ZEN_API_KEY }}
    steps:
        - name: Welcom Message
          run : |
            echo "Welcome to CI/CD "
        - name: Checkout code
          uses: actions/checkout@v4
        - name: List Folders
          run : |
            ls -la
            echo $test
        - name: Extract values from json file
          run: |
            newest_json=$(ls -t workflow/CO/*.json | head -n 1)
            server_url=$(jq -r '.server_url' $newest_json)
            snapshot_acronym=$(jq -r '.snapshot_acronym' $newest_json)
            project_short_name=$( jq -r '.project_short_name' $newest_json)
            snapshot_description=$( jq -r '.snapshot_description' $newest_json)
            snapshot_name=$( jq -r '.snapshot_name' $newest_json)
            project_name=$( jq -r '.project_name' $newest_json)
            echo "server_url=$server_url" >> $GITHUB_OUTPUT
            echo "snapshot_acronym=$snapshot_acronym" >> $GITHUB_OUTPUT
            echo "project_short_name=$project_short_name" >> $GITHUB_OUTPUT
            echo "snapshot_description=$snapshot_description" >> $GITHUB_OUTPUT
            echo "snapshot_name=$snapshot_name" >> $GITHUB_OUTPUT
            echo "project_name=$project_name" >> $GITHUB_OUTPUT
            echo "Project Name: $project_name"
            echo $ZEN_API_KEY
        - name: Get CSRF token
          run: |
            echo "Project Name: ${{ steps.extract_json.outputs.project_name }}"
            response=$(curl -s -X POST ${{ steps.extract_json.outputs.server_url }}/bas/ops/system/login \
            -H "Authorization: ZenApiKey $ZEN_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{ "refresh_groups": true, "requested_lifetime": 7200}')
            echo "Response: $response"
            csrfkey=$(echo "$response" | jq -r '.csrf_token')
            echo "Extracted csrfkey: $csrfkey"
            echo "csrfkey=$csrfkey" >> $GITHUB_OUTPUT