name: CI/CD for KVR Demo Process 

on:
  push:
    branches: [ main ]
    paths:
      - 'workflow/KVRDP/**.json'
  workflow_dispatch:

jobs:
  install_package:
    runs-on: ubuntu-latest
    env:
      ZEN_API_KEY: ${{ secrets.ZEN_API_KEY }}
    steps:
        - name: Welcom Message
          run : |
            echo "Welcome to CI/CD "